version: '3.8'

services:
  eventix-api:
    build: .
    container_name: eventix-api-container
    ports:
      - "3000:3000"
    environment:
      - JWT_SECRET=tu-secreto-super-seguro
    volumes:
      - ./data:/app/data
    restart: always